django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('it_platform/', include('it_platform.urls')),
    path('admin/', admin.site.urls),
]

django_app/it_platform/urls.py
from django.urls import path

from . import views


app_name = "it_platform"
urlpatterns = [
    path('', views.index, name='index'),
    path('app_details/<int:application_id>', views.app_details, name='app_details'),
    path('server_details/<int:server_id>', views.server_details, name='server_details'),
    path('frameworks', views.frameworks, name='frameworks'),
    path('operatingSystems', views.operatingSystems, name='operatingSystems'),
    path('servers', views.servers, name='servers'),
    path('databases', views.databases, name='databases'),
    path('database_details/<int:database_id>', views.database_details, name='database_details')
]

django_app/it_platform/models.py
from email.mime import application
from django.db import models

class OperatingSystem(models.Model):
    class Meta:
        db_table = u'"it\".\"operating_systems"'

    FAMILIES = [('WI', 'Windows'), ('LI', 'Linux'), ('MA', 'macOS'), ('UN', 'Unix'), ('VM','VMware'), ('AWS','AWS'), ('AZ','Azure'),]

    family = models.CharField(
        max_length=3,
        choices=FAMILIES,
        default='WI',
    )
    version = models.CharField(max_length=30)
    edition = models.CharField(max_length=30)
    distribution = models.CharField(max_length=30, blank=True)
    compilation = models.CharField(max_length=30, blank=True)
    architecture = models.CharField(max_length=30, blank=True)
    releaseDate = models.DateField(db_column='release_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    supportEndDate = models.DateField(db_column='support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    extendedSupportEndDate = models.DateField(db_column='extended_support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.get_family_display() +" "+ self.version +" ("+ self.edition + ")"


class Server(models.Model):
    class Meta:
        db_table = u'"it\".\"servers"'

    name = models.CharField(max_length=30, unique=True)
    operatingSystem = models.ForeignKey(OperatingSystem, on_delete=models.CASCADE, db_column='operating_system_id')
    details = models.CharField(max_length=200, blank=True)
    host = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True)
    processors = models.CharField(max_length=200, blank=True)
    physicalMemoryGB = models.CharField(db_column='physical_memory_gb', max_length=200, blank=True)
    storageGB = models.CharField(db_column='storage_gb', max_length=200, blank=True)
    category = models.CharField(max_length=200, blank=True)
    state = models.CharField(max_length=200, blank=True)
    environment = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.name


class DBManagementSystem(models.Model):
    class Meta:
        db_table = u'"it\".\"db_management_systems"'

    family = models.CharField(max_length=30)
    version = models.CharField(max_length=30)
    edition = models.CharField(max_length=30)
    compilation = models.CharField(max_length=30, blank=True)
    architecture = models.CharField(max_length=30, blank=True)
    type = models.CharField(max_length=30, blank=True)
    releaseDate = models.DateField(db_column='release_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    supportEndDate = models.DateField(db_column='support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    extendedSupportEndDate = models.DateField(db_column='extended_support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.family +" "+ self.version +" "+ self.edition


class Database(models.Model):
    class Meta:
        db_table = u'"it\".\"databases"'

    name = models.CharField(max_length=100, null=False, unique=True)
    DBManagementSystem = models.ManyToManyField(DBManagementSystem, through='DatabaseInstance', db_column='db_management_system_id')
    highAvailabilityType = models.CharField(db_column='high_availability_type', max_length=30, blank=True)
    server = models.ManyToManyField(Server, through='DatabaseInstance')

    def __str__(self):
        return self.name

    def databaseInstances(self):
        return DatabaseInstance.objects.filter(server__in=self.server.all(), database=self)


class BusinessUnit(models.Model):
    class Meta:
        db_table = u'"it\".\"business_units"'

    name = models.CharField(max_length=35, null=False)
    details = models.CharField(max_length=200, blank=True,null=True)

    def __str__(self):
        return self.name


class Framework(models.Model):
    class Meta:
        db_table = u'"it\".\"frameworks"'

    name = models.CharField(max_length=30)
    version = models.CharField(max_length=30)
    language = models.CharField(max_length=30, blank=True)
    type = models.CharField(max_length=30, blank=True)
    license = models.CharField(max_length=30, blank=True)
    releaseDate = models.DateField(db_column='release_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    supportEndDate = models.DateField(db_column='support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    extendedSupportEndDate = models.DateField(db_column='extended_support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.name +" - "+ self.version


class Application(models.Model):
    class Meta:
        db_table = u'"it\".\"applications"'
        constraints = [
            models.UniqueConstraint(fields=['businessUnit', 'codeID', 'name', 'type'], name='unique_application')
        ]
    
    MISSION_CRITICAL_CATEGORIES = [
        ('HI', 'High'),
        ('ME', 'Medium'),
        ('LO', 'Low'),
    ]

    businessUnit = models.ForeignKey(BusinessUnit, on_delete=models.CASCADE, db_column='business_unit_id')
    codeID = models.CharField(max_length=30, unique=True, db_column='code_id')
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    type = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=30, blank=True)
    missionCritical = models.CharField(
        max_length=2,
        choices=MISSION_CRITICAL_CATEGORIES,
        default='LO',
        blank=True,
        db_column='mission_critical'
    )
    category = models.CharField(max_length=30, blank=True)
    highAvailabilityType = models.CharField("High availability type", db_column='high_availability_type', max_length=30, blank=True)
    releaseDate = models.DateField("Release date", db_column='release_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    supportEndDate = models.DateField("Support end date", db_column='support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    extendedSupportEndDate = models.DateField("Extended support end date", db_column='extended_support_end_date', auto_now=False, auto_now_add=False, blank=True, null=True)
    version = models.CharField(max_length=30, blank=True)
    edition = models.CharField(max_length=30, blank=True)
    compilation = models.CharField(max_length=30, blank=True)
    server = models.ManyToManyField(Server, through='ApplicationInstance')
    framework = models.ManyToManyField(Framework, through='ApplicationInstance')
    database = models.ManyToManyField(Database, through='DatabaseInstance')

    def __str__(self):
        return self.name +" - "+ self.codeID

    def appInstances(self):
        return ApplicationInstance.objects.filter(server__in=self.server.all(), application=self)


class ApplicationInstance(models.Model):
    class Meta:
        db_table = u'"it\".\"application_instance"'
        constraints = [
            models.UniqueConstraint(fields=['application', 'server', 'framework', 'appInstance'], name='unique_application_instance')
        ]
    
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    framework = models.ForeignKey(Framework , on_delete=models.CASCADE)
    appInstance = models.CharField(db_column='app_instance', max_length=50, default='DEFAULT')
    createdAt = models.DateTimeField(db_column='created_at', auto_now=False, auto_now_add=True)
    updatedAt = models.DateTimeField(db_column='updated_at', auto_now=True, auto_now_add=False)
    removedAt = models.DateTimeField(db_column='removed_at', auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.application.name +" - "+ self.server.name +" - "+ self.framework.version


class DatabaseInstance(models.Model):
    class Meta:
        db_table = u'"it\".\"database_instance"'
        constraints = [
            models.UniqueConstraint(fields=['database', 'server', 'application', 'dbInstance'], name='unique_database_instance')
        ]
    
    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    dbInstance = models.CharField(db_column='db_instance', max_length=50, default='DEFAULT')
    DBManagementSystem = models.ForeignKey(DBManagementSystem, on_delete=models.CASCADE, null=True, blank=True, db_column='db_management_system_id')
    state = models.CharField(max_length=30, blank=True)
    createdAt = models.DateTimeField(db_column='created_at', auto_now=False, auto_now_add=True)
    updatedAt = models.DateTimeField(db_column='updated_at', auto_now=True, auto_now_add=False)
    removedAt = models.DateTimeField(db_column='removed_at', auto_now=False, auto_now_add=False, blank=True, null=True)

    def __str__(self):
        return self.database.name +" <-> "+ self.server.name

django_app/it_platform/views.py
from django.shortcuts import get_object_or_404, render

from .models import Application, Server, Framework, OperatingSystem, Database


def index(request):
    application_list = Application.objects.all().order_by('id')
    return render(request, "it_platform/applications.html", {
        "application_list": application_list
    })


def app_details(request, application_id):
    application = get_object_or_404(Application, pk=application_id)
    return render(request, "it_platform/app_details.html", {
        "application": application
    })


def server_details(request, server_id):
    server = get_object_or_404(Server, pk=server_id)
    return render(request, "it_platform/server_details.html", {
        "server": server
    })

def frameworks(request):
    framework_list = Framework.objects.all().order_by('name', 'version')
    return render(request, "it_platform/frameworks.html", {
        "framework_list": framework_list
    })

def operatingSystems(request):
    os_list = OperatingSystem.objects.all().order_by('family', 'version')
    return render(request, "it_platform/operating_systems.html", {
        "os_list": os_list
    })

def servers(request):
    server_list = Server.objects.all().order_by('name')
    return render(request, "it_platform/servers.html", {
        "server_list": server_list
    })

def databases(request):
    db_list = Database.objects.all().order_by('name')
    return render(request, "it_platform/databases.html", {
        "db_list": db_list
    })

def database_details(request, database_id):
    database = get_object_or_404(Database, pk=database_id)
    return render(request, "it_platform/database_details.html", {
        "database": database
    })

django_app/it_platform/templates/it_platform/applications.html
{% extends 'it_platform/base.html' %}
{% load static %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h1">Applications</h1>
        {% if application_list %}
        <div class="btn-toolbar mb-2 mb-md-0">
            <p class="lead mb-2">
                Applications: <b> {{ application_list.count }} </b>
            </p>
        </div>
        {% endif %}
    </div>
    {% if application_list %}
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">App Code</th>
                        <th scope="col">Type</th>
                        <th scope="col">State</th>
                        <th scope="col">Mission Critical</th>
                        <th scope="col">Category</th>
                        <th scope="col">Business Unit</th>
                    </tr>
                </thead>
                    <tbody>
                        {% for application in application_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>
                                <a href=" {% url 'it_platform:app_details' application.id %} ">
                                    {{ application.name }}
                                </a>
                            </td>
                            <td>{{ application.codeID }}</td>
                            <td>{{ application.Type }}</td>
                            <td>{{ application.State }}</td>
                            <td>{{ application.missionCritical }}</td>
                            <td>{{ application.category }}</td>
                            <td>{{ application.businessUnit }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>
    {% else %}
        <p>Empty application set</p>
    {% endif %}
{% endblock content %}

django_app/it_platform/templates/it_platform/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <title>IT Platform</title>

        {% load static %}
        <link href=" {% static 'it_platform/css/bootstrap.min.css' %} " rel="stylesheet">

        <!-- Custom styles for this template -->
        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                font-size: 3.5rem;
                }
            }

            .b-example-divider {
                height: 3rem;
                background-color: rgba(0, 0, 0, .1);
                border: solid rgba(0, 0, 0, .15);
                border-width: 1px 0;
                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
            }

            .b-example-vr {
                flex-shrink: 0;
                width: 1.5rem;
                height: 100vh;
            }

            .bi {
                vertical-align: -.125em;
                fill: currentColor;
            }

            .nav-scroller {
                position: relative;
                z-index: 2;
                height: 2.75rem;
                overflow-y: hidden;
            }

            .nav-scroller .nav {
                display: flex;
                flex-wrap: nowrap;
                padding-bottom: 1rem;
                margin-top: -1px;
                overflow-x: auto;
                text-align: center;
                white-space: nowrap;
                -webkit-overflow-scrolling: touch;
            }
        </style>

        <link href=" {% static 'it_platform/css/dashboard.css' %} " rel="stylesheet">

    </head>
    <body>
    
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-center" href="#">Compensar - IT Platform</a>
            <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
            <div class="navbar-nav">
                <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="{% url 'admin:index' %}">Sign in</a>
                </div>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
                    <div class="position-sticky pt-3 sidebar-sticky p-2">
                        <ul class="nav flex-column list-group list-group-flush">
                            <li class="nav-item list-group-item list-group-item-action">
                                <a class="nav-link" aria-current="page" href=" {% url 'it_platform:index' %} "> 
                                    <img class="align-text-bottom" src=" {% static 'it_platform/icons/app.svg' %} ">
                                    Applications
                                </a>
                            </li>
                            <li class="nav-item list-group-item list-group-item-action">
                                <a class="nav-link" href=" {% url 'it_platform:frameworks' %} ">
                                    <img class="align-text-bottom" src=" {% static 'it_platform/icons/file-code.svg' %} ">
                                    Frameworks
                                </a>
                            </li>
                            <li class="nav-item list-group-item list-group-item-action">
                                <a class="nav-link" href=" {% url 'it_platform:operatingSystems' %} ">
                                    <img class="align-text-bottom" src=" {% static 'it_platform/icons/stack.svg' %} ">
                                    Operating Systems
                                </a>
                            </li>
                            <li class="nav-item list-group-item list-group-item-action">
                                <a class="nav-link" href=" {% url 'it_platform:servers' %} ">
                                    <img class="align-text-bottom" src=" {% static 'it_platform/icons/cpu.svg' %} ">
                                    Servers
                                </a>
                            </li>
                            <li class="nav-item list-group-item list-group-item-action">
                                <a class="nav-link" href=" {% url 'it_platform:databases' %} ">
                                    <img class="align-text-bottom" src=" {% static 'it_platform/icons/layers.svg' %} ">
                                    Databases
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    {% block content %}
                    {% endblock content %}
                </main>
            </div>
        </div>

        <script src=" {% static 'it_platform/js/bootstrap.bundle.min.js' %} "></script>
    </body>
</html>

django_app/it_platform/templates/it_platform/databases.html
{% extends 'it_platform/base.html' %}
{% load static %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h1">Databases</h1>
        {% if db_list %}
        <div class="btn-toolbar mb-2 mb-md-0">
            <p class="lead mb-2">
                Databases: <b> {{ db_list.count }} </b>
            </p>
        </div>
        {% endif %}
    </div>
    {% if db_list %}
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">name</th>
                        <th scope="col">High Availability Type</th>
                        <th scope="col">Applications</th>
                        <th scope="col">DB Instances</th>
                        <th scope="col">Servers</th>
                    </tr>
                </thead>
                    <tbody>
                        {% for database in db_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href=" {% url 'it_platform:database_details' database.id %} ">{{ database.name }}</a></td>
                            <td>{{ database.highAvailabilityType }}</td>
                            <td>{{ database.application_set.distinct.count }}</td>
                            <td>{{ database.databaseInstances.count }}</td>
                            <td>{{ database.server.distinct.count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
        </div>
    {% else %}
        <p>Empty database set</p>
    {% endif %}
{% endblock content %}

django_app/it_platform/templates/it_platform/server_details.html
{% extends 'it_platform/base.html' %}
{% load static %}
{% block content %}
    {% if server %}
                
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h1">
            {{ server.name }}
            <a class="btn btn-outline-secondary btn-sm" data-bs-toggle="collapse" href="#ServerDetails" role="button" aria-expanded="false" aria-controls="ServerDetails">
                <img class="align-text-bottom" src=" {% static 'it_platform/icons/info-lg.svg' %} ">
            </a>
        </h1>
    </div>

    <div class="container-fluid">
        <div class="collapse" id="ServerDetails">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Server details</h5>
                    <p class="text-muted"> {{ server.details }} </p>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-sm table-borderless">
                        <thead>
                            <tr>
                                <th scope="col">Operating System</th>
                                <th scope="col">Host</th>
                                <th scope="col">Location</th>
                                <th scope="col">Processors</th>
                                <th scope="col">Memory GB</th>
                                <th scope="col">Storage GB</th>
                                <th scope="col">Category</th>
                                <th scope="col">State</th>
                                <th scope="col">Environment</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ server.operatingSystem }}</td>
                                <td>{{ server.host }}</td>
                                <td>{{ server.location }}</td>
                                <td>{{ server.processors }}</td>
                                <td>{{ server.physicalMemoryGB }}</td>
                                <td>{{ server.storageGB }}</td>
                                <td>{{ server.category }}</td>
                                <td>{{ server.state }}</td>
                                <td>{{ server.environment }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <br>
        </div>
        {% comment %} ---------------------------------- {% endcomment %}
        <div class="card">
            <div class="card-header">
                <div class="nav nav-tabs card-header-tabs " id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-app-inst-tab" data-bs-toggle="tab" data-bs-target="#nav-app-inst" type="button" role="tab" aria-controls="nav-app-inst" aria-selected="true">
                        Application Instances
                        {% comment %} <span class="badge rounded-pill text-bg-primary">
                            {% trans 0 as value %}
                            {% for app in server.application_set.all.distinct %}
                                {% for inst in app.appInstances. %}
                                    {% if inst.server_id == server.id %}
                                        {{ value|add:1 }}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %} {% endcomment %}
                        </span>
                    </button>
                    <button class="nav-link" id="nav-db-inst-tab" data-bs-toggle="tab" data-bs-target="#nav-db-inst" type="button" role="tab" aria-controls="nav-db-inst" aria-selected="false">Database Instances</button>
                </div>
            </div>
            <div class="card-body">
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-app-inst" role="tabpanel" aria-labelledby="nav-app-inst-tab" tabindex="0">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Application</th>
                                        <th scope="col">Code ID</th>
                                        <th scope="col">Type</th>
                                        <th scope="col">State</th>
                                        <th scope="col">Category</th>
                                        <th scope="col">Version</th>
                                        <th scope="col">Edition</th>
                                        <th scope="col">Instance | Framework</th>
                                    </tr>
                                </thead>
                                <tbody class="align-middle">
                                    {% for application in server.application_set.distinct %}           
                                    <tr>
                                        <td>
                                            <a href=" {% url 'it_platform:app_details' application.id %} ">
                                                {{ application.name }}
                                            </a>
                                        </td>
                                        <td>{{ application.codeID }}</td>
                                        <td>{{ application.type }}</td>
                                        <td>{{ application.state }}</td>
                                        <td>{{ application.category }}</td>
                                        <td>{{ application.version }}</td>
                                        <td>{{ application.edition }}</td>
                                        <td>{% for instance in application.appInstances %}
                                                {% if instance.server_id == server.id %}
                                                    <ol class="breadcrumb">
                                                        <li class="breadcrumb-item">{{ instance.appInstance }}</li>
                                                        <li class="breadcrumb-item active">{{ instance.framework }}</li>
                                                    </ol>
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="nav-db-inst" role="tabpanel" aria-labelledby="nav-db-inst-tab" tabindex="0">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Instance</th>
                                        <th scope="col">Database</th>
                                        <th scope="col">Application</th>
                                        <th scope="col">High Availability Type</th>
                                        <th scope="col">State</th>
                                        <th scope="col">DB Engine</th>
                                    </tr>
                                </thead>
                                <tbody class="align-middle">
                                    {% for database in server.database_set.distinct %}           
                                        {% for instance in database.databaseInstances %}
                                            {% if instance.server_id == server.id %}
                                            <tr>
                                                <td>
                                                    <ol class="breadcrumb">
                                                        <li class="breadcrumb-item">
                                                            <a href=" {% url 'it_platform:server_details' instance.server.id %} "></a> {{ instance.server.name }}
                                                        </li>
                                                        <li class="breadcrumb-item active">{{ instance.dbInstance }}</li>
                                                    </ol>
                                                </td>
                                                <td><a href="{% url 'it_platform:database_details' database.id %}">{{ database.name }}</a></td>
                                                <td>
                                                    <li><a href=" {% url 'it_platform:app_details' instance.application_id %} ">{{ instance.application }}</a></li>
                                                </td>
                                                <td>{{ database.highAvailabilityType }}</td>
                                                <td>{{ instance.state }}</td>
                                                <td>{{ instance.DBManagementSystem }}</td>
                                            </tr>
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>

    {% endif %}
{% endblock content %}